anomaly_degree,content
0.2,"INFO	Diagnostics report from attempt_1701398500430_0101_m_000002_0: [2023-12-01 15:23:05.746]Exception when trying to cleanup container container_1701398500430_0101_01_000006: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701398500430_0101/container_1701398500430_0101_01_000006/container_1701398500430_0101_01_000006.pid (No such file or directory)	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.apache.hadoop.yarn.server.nodemanager.util.ProcessIdFileReader.getProcessId(ProcessIdFileReader.java:59)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.getContainerPid(ContainerLaunch.java:1035)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerCleanup.run(ContainerCleanup.java:120)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)"
