name,value,relevant log,explanation
fs.s3a.committer.threads,8,INFO	Diagnostics report from attempt_1701398500430_0101_m_000002_0: [2023-12-01 15:23:05.746]Exception when trying to cleanup container container_1701398500430_0101_01_000006: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701398500430_0101/container_1701398500430_0101_01_000006/container_1701398500430_0101_01_000006.pid (No such file or directory)	,value-hit
yarn.nm.liveness-monitor.expiry-interval-ms,600000,INFO	Diagnostics report from attempt_1701398500430_0101_m_000002_0: [2023-12-01 15:23:05.746]Exception when trying to cleanup container container_1701398500430_0101_01_000006: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701398500430_0101/container_1701398500430_0101_01_000006/container_1701398500430_0101_01_000006.pid (No such file or directory)	,property-item-hit	nm
dfs.datanode.fsdatasetasyncdisk.max.threads.per.volume,4,INFO	Diagnostics report from attempt_1701398500430_0101_m_000002_0: [2023-12-01 15:23:05.746]Exception when trying to cleanup container container_1701398500430_0101_01_000006: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701398500430_0101/container_1701398500430_0101_01_000006/container_1701398500430_0101_01_000006.pid (No such file or directory)	,value-hit
dfs.namenode.reencrypt.edek.threads,10,INFO	Diagnostics report from attempt_1701398500430_0101_m_000002_0: [2023-12-01 15:23:05.746]Exception when trying to cleanup container container_1701398500430_0101_01_000006: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701398500430_0101/container_1701398500430_0101_01_000006/container_1701398500430_0101_01_000006.pid (No such file or directory)	,value-hit
dfs.client.refresh.read-block-locations.threads,5,INFO	Diagnostics report from attempt_1701398500430_0101_m_000002_0: [2023-12-01 15:23:05.746]Exception when trying to cleanup container container_1701398500430_0101_01_000006: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701398500430_0101/container_1701398500430_0101_01_000006/container_1701398500430_0101_01_000006.pid (No such file or directory)	,value-hit
dfs.qjournal.queued-edits.limit.mb,10,INFO	Diagnostics report from attempt_1701398500430_0101_m_000002_0: [2023-12-01 15:23:05.746]Exception when trying to cleanup container container_1701398500430_0101_01_000006: java.io.FileNotFoundException: /home/hadoop3/hadoop/tmp/nm-local-dir/nmPrivate/application_1701398500430_0101/container_1701398500430_0101_01_000006/container_1701398500430_0101_01_000006.pid (No such file or directory)	,value-hit
